version: '3'
services:
  webserver:
    image: nginx:1.18.0
    container_name: "nginx"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:8080"
      - "443:8443"
